Updated work flows lts
zowe/zowe-cli-db2-plugin pull request #124
Opened 2023-05-05 19:25 UTC by ATorrise

Action | Description
-- | --									
#6 | [update all workflows to remove deprecation warnings](https://github.com/zowe/zowe-cli-web-help-generator/pull/35/files), [octorelease updates](https://github.com/zowe/zowe-cli/pull/1712)										
#7 | remove Node 14 from workflow matrix

2023-05-08 14:49 UTC, zFernand0 requested changes
LGTM! 😋 
just 2 small things to update 😅

2023-05-08 14:49 UTC, zFernand0 commented on .github/workflows/changelog.yml
Could we change the `awharn/check_changelog_action@v0.0.2` to v1 here as well?

2023-05-08 14:49 UTC, zFernand0 commented on .github/workflows/codeql.yml
> -      uses: github/codeql-action/init@v1
thanks for changing the `init`
could you also update the `analyze`? 😋 
https://github.com/github/codeql-action#usage

2023-05-09 04:05 UTC, t1m0thyj requested changes

2023-05-09 04:05 UTC, t1m0thyj commented on .github/workflows/changelog.yml
> +      uses: awharn/check_changelog_action@1
This should be `@v1`

2023-05-09 04:05 UTC, t1m0thyj commented on .github/workflows/zowe-cli-plugin.yml
> +      uses: actions/checkout@v3s
This should be `@v3`

2023-05-10 14:36 UTC, zFernand0 approved these changes

2023-05-11 16:07 UTC, t1m0thyj approved these changes

2023-05-11 16:07 UTC, merged