Add an example for passing outputs from an sp
zowe/zowe-cli-db2-plugin pull request #66
Opened 2020-12-03 21:57 UTC by BrandonJenkins14

Added example to the `zowe db2 call sp` command.

Q: Is the description too long to display OK in a command line? I think it helps to describe the purpose of the 00 and message_placeholder. Maybe this is obvious to CLI users and doesn't need to be pointed out though. 

Signed-off-by: Brandon Jenkins <36675406+BrandonJenkins14@users.noreply.github.com>

2020-12-03 22:01 UTC, BrandonJenkins14 commented
FYI I'm not sure if I incremented the changlog release number correctly (to 4.0.8). Lmk if there is anything I should keep in mind when adding new entries like that. Thx!

2020-12-04 12:57 UTC, t1m0thyj requested changes

2020-12-04 12:57 UTC, t1m0thyj commented on CHANGELOG.md
> +## `4.0.8`
Header should be "Recent Changes" instead of "`4.0.8`". When the PR is merged the version automatically gets updated here.

2020-12-04 12:57 UTC, t1m0thyj commented on src/cli/call/procedure/Procedure.definition.ts
> +            options: "\"DEMO.SP3(NULL, ?, ?)\" --parameters "00" "message_placeholder_message_placeholder"",
All the quotes inside the string need to be escaped:
```javascript
options: "\"DEMO.SP3(NULL, ?, ?)\" --parameters \"00\" \"message_placeholder_message_placeholder\"",
```
Alternatively you can use backticks:
```javascript
options: `"DEMO.SP3(NULL, ?, ?)" --parameters "00" "message_placeholder_message_placeholder"`,
```

Either way should make the linter happy 🙂

2020-12-10 18:08 UTC, awharn approved these changes
This looks good to me.

2020-12-10 18:09 UTC, awharn requested changes
spotted a problem on second glance - could you please update the unit test snapshot that is failing?

2020-12-14 13:53 UTC, awharn approved these changes
LGTM 👍🏼

2020-12-17 17:23 UTC, t1m0thyj approved these changes

2020-12-17 17:42 UTC, merged